import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${inter.variable} ${inter.variable} h-full antialiased`} suppressHydrationWarning>
			<head />
			<body className='min-h-full flex flex-col' suppressHydrationWarning>
				<ThemeProvider attribute='class'>{children}</ThemeProvider>
			</body>
		</html>
	);
}
